import StyleDictionary from "style-dictionary"
import type { FormatFn, TransformedToken } from "style-dictionary/types"

/**
 * Dark tokens have "dark" or "*-dark" as the second path segment.
 * semantic.dark.surface → dark override for --semantic-surface
 * semantic.shadow-dark.sm → dark override for --semantic-shadow-sm
 * semantic.editor-dark.caret → dark override for --semantic-editor-caret
 * semantic.toast-dark.info-bg → dark override for --semantic-toast-info-bg
 */
function isDarkToken(token: TransformedToken): boolean {
  if (token.path[0] !== "semantic") return false
  const segment = token.path[1]
  if (!segment) return false
  return segment === "dark" || segment.endsWith("-dark")
}

/**
 * Convert token path to CSS variable name.
 * Primitives: primitive.color.gray.50 → --primitive-color-gray-50
 * Semantics: semantic.surface → --semantic-surface
 * Dark tokens map to their light counterpart name:
 *   semantic.dark.surface → --semantic-surface
 *   semantic.shadow-dark.sm → --semantic-shadow-sm
 *   semantic.editor-dark.caret → --semantic-editor-caret
 *   semantic.toast-dark.info-bg → --semantic-toast-info-bg
 */
function toVarName(token: TransformedToken): string {
  if (!isDarkToken(token)) {
    return `--${token.path.join("-")}`
  }
  const segment = token.path[1]
  if (!segment) return `--${token.path.join("-")}`
  if (segment === "dark") {
    return `--semantic-${token.path.slice(2).join("-")}`
  }
  const lightKey = segment.replace(/-dark$/, "")
  return `--semantic-${lightKey}-${token.path.slice(2).join("-")}`
}

/**
 * Format token value, converting Style Dictionary references to CSS var().
 * {primitive.color.gray.50} → var(--primitive-color-gray-50)
 * {semantic.primary} → var(--semantic-primary)
 * Literal values (OKLCH, px, rem) pass through unchanged.
 */
function formatValue(token: TransformedToken): string {
  const original = token.original.value as string
  if (typeof original === "string" && original.includes("{")) {
    return original.replace(/\{([^}]+)\}/g, (_, ref: string) => `var(--${ref.replace(/\./g, "-")})`)
  }
  return token.value
}

/**
 * Group tokens by logical category for CSS comments.
 */
function getCategoryKey(token: TransformedToken): string {
  const [p0, p1] = token.path
  if (p0 === "primitive" && p1) return `${p0}.${p1}`
  if (p0 === "semantic") {
    if (token.path.length === 2) return "semantic"
    if (p1) return `${p0}.${p1}`
  }
  return p0 ?? "unknown"
}

function renderBlock(tokens: TransformedToken[], indent: string): string[] {
  const categories = new Map<string, TransformedToken[]>()
  for (const token of tokens) {
    const key = isDarkToken(token) ? (token.path[1] ?? "unknown") : getCategoryKey(token)
    if (!categories.has(key)) {
      categories.set(key, [])
    }
    categories.get(key)?.push(token)
  }

  const lines: string[] = []
  const entries = [...categories.entries()]
  for (const [i, [category, catTokens]] of entries.entries()) {
    const first = catTokens[0]
    const label = first && isDarkToken(first) ? `${category} overrides` : category
    lines.push(`${indent}/* ${label} */`)
    for (const token of catTokens) {
      lines.push(`${indent}${toVarName(token)}: ${formatValue(token)};`)
    }
    if (i < entries.length - 1) lines.push("")
  }
  return lines
}

const cssVariablesFormat: FormatFn = ({ dictionary }) => {
  const rootTokens: TransformedToken[] = []
  const darkTokens: TransformedToken[] = []

  for (const token of dictionary.allTokens) {
    if (isDarkToken(token)) {
      darkTokens.push(token)
    } else {
      rootTokens.push(token)
    }
  }

  const lines: string[] = [
    "/* Generated by Style Dictionary - DO NOT EDIT */",
    "/* Source: frontend/packages/theme/src/tokens */",
    "",
    ":root {",
    ...renderBlock(rootTokens, "  "),
    "}",
  ]

  if (darkTokens.length > 0) {
    // Manual toggle: [data-theme="dark"]
    lines.push("")
    lines.push("/* Dark mode - Manual toggle via data-theme attribute */")
    lines.push('[data-theme="dark"] {')
    lines.push(...renderBlock(darkTokens, "  "))
    lines.push("}")

    // System preference fallback
    lines.push("")
    lines.push("/* System preference fallback (when no manual selection) */")
    lines.push("@media (prefers-color-scheme: dark) {")
    lines.push('  :root:not([data-theme="light"]):not([data-theme="dark"]) {')
    lines.push(...renderBlock(darkTokens, "    "))
    lines.push("  }")
    lines.push("}")
  }

  return `${lines.join("\n")}\n`
}

StyleDictionary.registerFormat({
  name: "custom/css-variables",
  format: cssVariablesFormat,
})

const config = {
  // Token name collisions are expected: the default `name` transform
  // truncates paths (e.g. gray.50 vs blue.50 → "50"), but our custom
  // format uses the full `token.path` for CSS variable names, so the
  // actual output is correct. Suppress the false-positive warnings.
  log: { warnings: "disabled" as const },
  source: ["src/tokens/**/*.json"],
  platforms: {
    css: {
      buildPath: "src/generated/",
      files: [{ destination: "tokens.css", format: "custom/css-variables" }],
    },
  },
}

const sd = new StyleDictionary(config)
console.log("Building design tokens...")
await sd.buildAllPlatforms()
console.log("Design tokens built successfully!")
